---
- name: remove all
  hosts: localhost
  gather_facts: false
  ignore_errors: true
  vars:
    vserver1: svm1
    vserver2: svm2
    peer_cluster: cluster1
    dest_hostname: 192.168.0.101
    cluster: cluster2
    login1: &login1
     hostname: 192.168.0.101
     username: admin
     password: Netapp1!
     https: true
     validate_certs: false
    login2: &login2
     hostname: 192.168.0.102
     username: admin
     password: Netapp1!
     https: true
     validate_certs: false
  tasks:
  - name: delete snapmirror
    na_ontap_command:
      command: ['snapmirror delete *']
      privilege: admin
      <<: *login2
  - name: remove vserver peering
    na_ontap_vserver_peer:
      state: absent
      peer_vserver: "{{ vserver1 }}"
      peer_cluster: "{{ peer_cluster }}"
      vserver: "{{ vserver1 }}"
      applications: snapmirror
      <<: *login2
  - name: remove cluster peering
    na_ontap_cluster_peer:
      state: absent
      dest_cluster_name: "{{ peer_cluster }}"
      source_cluster_name: "{{ cluster }}"
      dest_hostname: "{{ dest_hostname }}"
      <<: *login2
  - name: Gather facts
    na_ontap_info:
      state: info
      gather_subset:
      - net_interface_info
      - volume_info
      <<: *login1
    register: netapp1
  - name: Gather facts
    na_ontap_info:
      state: info
      gather_subset:
      - net_interface_info
      - volume_info
      <<: *login2
    register: netapp2
  - name: Unset NTP on cluster1
    na_ontap_ntp:
      state: absent
      version: auto
      server_name: "{{ ntpservers }}"
      <<: *login1
  - name: Unset NTP on cluster2
    na_ontap_ntp:
      state: absent
      version: auto
      server_name: "{{ ntpservers }}"
      <<: *login1
  - name: Set Timezone Default cluster1
    na_ontap_command:
      command: ['time', '-timezone', 'UTC']
      privilege: admin
      <<: *login1
  - name: Set Timezone Default cluster2
    na_ontap_command:
      command: ['time', '-timezone', 'UTC']
      privilege: admin
      <<: *login2
  - name: remove lifs cluster1 - svm1
    na_ontap_interface:
      state: absent
      interface_name: "{{ netapp1.ontap_info.net_interface_info[item].interface_name }}"
      vserver: "{{ vserver }}"
      <<: *login1
    with_items: "{{ netapp1.ontap_info.net_interface_info }}"
    when:
    - "{{ netapp1.ontap_info.net_interface_info[item].vserver == vserver1 }}"
    ignore_errors: yes
  - name: remove vols cluster1 - svm1
    na_ontap_volume:
      state: absent
      name:  "{{ netapp1.ontap_info.volume_info[item].volume_id_attributes.name }}"
      vserver: "{{ vserver1 }}"
      <<: *login1
    with_items: "{{ netapp.ontap_info.volume_info }}"
    when:
    - netapp1.ontap_info.volume_info[item].volume_id_attributes.owning_vserver_name == "{{ vserver1 }}"
    - not (netapp1.ontap_info.volume_info[item].volume_id_attributes.name).endswith('root')
    ignore_errors: yes
  - name: Remove Vserver on cluster1
    na_ontap_svm:
      state: absent
      name: "{{ vserver1 }}"
      <<: *login1
  - name: remove lifs cluster2 - svm2
    na_ontap_interface:
      state: absent
      interface_name: "{{ netapp2.ontap_info.net_interface_info[item].interface_name }}"
      vserver: "{{ vserver2 }}"
      <<: *login2
    with_items: "{{ netapp2.ontap_info.net_interface_info }}"
    when:
    - "{{ netapp2.ontap_info.net_interface_info[item].vserver == vserver2 }}"
    ignore_errors: yes
  - name: remove vols on cluster2 - svm2
    na_ontap_volume:
      state: absent
      name:  "{{ netapp2.ontap_info.volume_info[item].volume_id_attributes.name }}"
      vserver: "{{ vserver2 }}"
      <<: *login2
    with_items: "{{ netapp2.ontap_info.volume_info }}"
    when:
    - netapp2.ontap_info.volume_info[item].volume_id_attributes.owning_vserver_name == "{{ vserver2 }}"
    - not (netapp2.ontap_info.volume_info[item].volume_id_attributes.name).endswith('root')
    ignore_errors: yes
  - name: Remove Vserver on cluster2
    na_ontap_svm:
      state: absent
      name: "{{ vserver2 }}"
      <<: *login2
  - name: remove interface n1 cluster1
    na_ontap_interface:
     state: absent
     interface_name: peer-lif-n1
     vserver: cluster1
     <<: *login1
  - name: remove interface n2 cluster1
    na_ontap_interface:
     state: present
     interface_name: peer-lif-n2
     vserver: cluster1
     <<: *login1
  - name: remove interface n1 cluster2
    na_ontap_interface:
     state: absent
     interface_name: peer-lif-n1
     vserver: cluster2
     <<: *login2 
