############################################
# NetApp Learning Services / 2020
# global/private vars are in sanvars.yml
# playbook specific vars are down below
#############################################
---
- hosts: localhost
  gather_facts: false
  vars_files:
   global.yml
  vars:
    volname: "{{ VOL_NAME }}"
    vserver: "{{ PRI_SVM }}"
    aggr: "{{ PRI_AGGR }}"
    policy: Default
    state: present
  name: create_lun_all
  tasks:
   - name: create_igroup
     na_ontap_igroup:
          state: present
          name: "{{ IGROUP_NAME }}"
          initiator_group_type: iscsi
          ostype: windows
          initiator: "{{ WIN_IQN }}"
          vserver: "{{ PRI_SVM }}"
          hostname: "{{ PRI_CLU }}"
          username: "{{ PRI_CLU_USER }}"
          password: "{{ PRI_CLU_PASS }}"
   - name: create_lun
     na_ontap_lun:
          name: "{{ LUN_NAME }}"
          flexvol_name: "{{ VOL_NAME }}"
          size: 5
          size_unit: gb
          ostype: windows
          space_reserve: false
          vserver: "{{ PRI_SVM }}"
          hostname: "{{ PRI_CLU }}"
          username: "{{ PRI_CLU_USER }}"
          password: "{{ PRI_CLU_PASS }}"
   - name: lun_map
     na_ontap_lun_map:
          initiator_group_name: "{{ IGROUP_NAME }}"
          path:  /vol/{{ VOL_NAME }}/{{ LUN_NAME }}
          vserver: "{{ PRI_SVM }}"
          hostname: "{{ PRI_CLU }}"
          username: "{{ PRI_CLU_USER }}"
          password: "{{ PRI_CLU_PASS }}"
