---
- hosts: localhost
  gather_facts: false
  name: Setup ONTAP
  vars:
    login: &login
     hostname: 192.168.0.101 # NetApp Cluster IP
     username: admin # Cluster User
     password: Netapp1! # Cluster Password
     https: true
     validate_certs: false
  vars_files:
   - var_cluster1.yml
  tasks:
  - name: Gather facts
    na_ontap_info:
      state: info
      <<: *login
    register: netapp
  - name: Create Volume
    na_ontap_interface:
      state: absent
      name: "{{ item }}"
      vserver: svm1
      <<: *login
    register: result
    with_items: "{{ netapp.ontap_info.net_interface_info }}"
    when:
    - "{{ netapp.ontap_info.net_interface_info[item].vserver }}" = svm1
    ignore_errors: yes
