---
- hosts: localhost
  gather_facts: no
  vars_prompt:
  vars:
    input: &input
      hostname: "{{ PRI_CLU }}"
      username: "{{ PRI_CLU_USER }}"
      password: "{{ PRI_CLU_PASS }}"
    file: globals.vars
  tasks:
  - import_role:
      name: na_ontap_san_create
    vars:
      <<: *input
    when: luns != None
